; This is an empty music and it won't produce any sound output

; MUSIC SIZE = 27 (approximately)
; Generated by SF2 Music Cooker v1.00
; This output is from an automated tool, please avoid manual edits in it, instead it is better to improve/fix the tool!

Music_56:
		db 0	; Must be zero
		db 0	; DAC mode (0=YES, 1=NO)
		db 0	; Reserved
		db 0C8h	; YM Timer B (music tempo)
		dw Music_56_Channel_9
		dw Music_56_Channel_9
		dw Music_56_Channel_9
		dw Music_56_Channel_9
		dw Music_56_Channel_9
		dw Music_56_Channel_9
		dw Music_56_Channel_9
		dw Music_56_Channel_9
		dw Music_56_Channel_9
		dw Music_56_Channel_9

Music_56_Channel_9:
		channel_end
