; Generated by SF2 Music Cooker v0.7
; This output is from an automated tool, please avoid manual edits in it, instead it is better to improve/fix the tool!

Music_9:		; [CUSTOM: Test Replace]
		db 0	; Must be zero
		db 0	; DAC mode (1=YES, 0=NO)
		db 0	; Reserved
		db 75h	; YM Timer B (music tempo)
		dw Music_9_Channel_0
		dw Music_9_Channel_1
		dw Music_9_Channel_2
		dw Music_9_Channel_3
		dw Music_9_Channel_4
		dw Music_9_Channel_5
		dw Music_9_Channel_6
		dw Music_9_Channel_7
		dw Music_9_Channel_8
		dw Music_9_Channel_9

Music_9_Channel_0:
		stereo 0C0h
		mainLoopStart
		inst 40
		vol 0Fh
		setRelease 03h
		noteL D2,4
		note  D2
		note  D2
		note  D2
		note  D2
		note  D2
		note  D2
		note  D2
		note  D2
		note  D2
		note  D2
		note  D2
		note  D2
		note  D2
		note  D2
		noteL D2,5
		mainLoopEnd

Music_9_Channel_1:
		stereo 0C0h
		mainLoopStart
		inst 40
		vol 0Fh
		setRelease 01h
		noteL D4,2
		note  C4
		note  A3
		note  G3
		note  F3
		note  A3
		note  C4
		note  D4
		note  A3
		note  C4
		note  D4
		note  F4
		note  D4
		note  F4
		note  G4
		note  A4
		note  F4
		note  A4
		note  C5
		note  D5
		note  F5
		note  D5
		note  F5
		note  G5
		note  A5
		note  F5
		note  G5
		note  A5
		note  C6
		note  A5
		note  C6
		noteL D6,3
		mainLoopEnd

Music_9_Channel_2:
		stereo 0C0h
		mainLoopStart
		inst 40
		vol 0Fh
		setRelease 02h
		noteL F4,2
		note  D4
		note  C4
		note  A3
		note  G3
		note  F3
		note  A3
		note  C4
		note  D4
		note  A3
		note  C4
		note  D4
		note  F4
		note  D4
		note  F4
		note  G4
		note  A4
		note  F4
		note  A4
		note  C5
		note  D5
		note  F5
		note  D5
		note  F5
		note  G5
		note  A5
		note  F5
		note  G5
		note  A5
		note  C6
		note  A5
		setRelease 01h
		noteL C6,3
		mainLoopEnd

Music_9_Channel_3:
		stereo 0C0h
		mainLoopStart
		inst 40
		vol 0Fh
		setRelease 03h
		noteL D5,4
		setRelease 01h
		note  A4
		setRelease 03h
		note  A4
		note  D5
		setRelease 01h
		note  A4
		setRelease 03h
		note  A4
		note  D5
		setRelease 01h
		note  A4
		setRelease 03h
		note  A4
		note  D5
		setRelease 01h
		note  A4
		setRelease 03h
		note  A4
		note  D5
		setRelease 01h
		note  A4
		setRelease 03h
		note  A4
		noteL D5,5
		mainLoopEnd

Music_9_Channel_4:
		stereo 0C0h
		mainLoopStart
		inst 40
		vol 04h
		setRelease 03h
		noteL F5,4
		vol 03h
		setRelease 02h
		note  E5
		setRelease 01h
		note  D5
		vol 04h
		setRelease 03h
		note  E5
		vol 03h
		setRelease 02h
		note  D5
		setRelease 01h
		note  C5
		vol 04h
		setRelease 03h
		note  F5
		vol 03h
		setRelease 02h
		note  E5
		setRelease 01h
		note  D5
		vol 04h
		setRelease 03h
		note  G5
		vol 03h
		setRelease 02h
		note  F5
		setRelease 01h
		note  E5
		vol 04h
		setRelease 03h
		note  F5
		vol 03h
		setRelease 02h
		note  E5
		setRelease 01h
		note  D5
		noteL C5,5
		mainLoopEnd

Music_9_Channel_5:
		stereo 0C0h
		mainLoopStart
		inst 40
		vol 0Fh
		setRelease 03h
		noteL D5,4
		setRelease 02h
		note  C5
		setRelease 01h
		note  A4
		setRelease 03h
		note  C5
		setRelease 02h
		note  A4
		setRelease 01h
		note  G4
		setRelease 03h
		note  D5
		setRelease 02h
		note  C5
		setRelease 01h
		note  A4
		setRelease 03h
		note  E5
		setRelease 02h
		note  D5
		setRelease 01h
		note  C5
		setRelease 03h
		note  D5
		setRelease 02h
		note  C5
		setRelease 01h
		note  A4
		noteL G4,5
		mainLoopEnd

Music_9_Channel_6:
		channel_end

Music_9_Channel_7:
		channel_end

Music_9_Channel_8:
		channel_end

Music_9_Channel_9:
		channel_end

